baseURL = 'https://gsr114514.pages.dev/' # 之后 Cloudflare 会给你这个域名
languageCode = 'zh-cn'
title = '我的极客空间'
theme = 'PaperMod'

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"