baseURL = "https://mrruis-blog.pages.dev/"
languageCode = "zh-cn"
title = "Mr.Ruis的博客"
theme = "PaperMod"

[params]
    env = "production" # 强制告诉 Hugo 现在是正式环境

[params.profileMode]
    enabled = true
    title = "Mr.Ruis"
    subtitle = "技术记录与生活随笔。"
    displayname = "Mr.Ruis"
    # 注意这里：直接写 imageUrl = "路径"，不要再写子项目
    imageUrl = "/avatar.jpg" 
    imageWidth = 120
    imageHeight = 120


[[menu.main]]
    identifier = "posts"
    name = "文章"
    url = "/posts/"
    weight = 10

[[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/3461569883147060"

[[params.socialIcons]]
    name = "douyin"
    url = "https://www.douyin.com/user/你的ID"

[[params.socialIcons]]
    name = "github"
    url = "https://github.com/你的用户名"

[[params.socialIcons]]
    name = "email"
    url = "mailto:你的邮箱@example.com"